ctdatabase:
    restart: always
    dockerfile: database/Dockerfile
    build: .
    entrypoint: /config.sh
    volumes:
        - /mnt/data/ct-monitor/data:/var/lib/postgresql/data
    ports:
        - 5432:5432
    command: postgres

ctmonitor:
    restart: always
    dockerfile: monitor/Dockerfile
    build: .
    links:
        - ctdatabase:ctdatabase
    command: ./ct-monitor

ctobservatory:
    restart: always
    dockerfile: observatory/Dockerfile
    build: .
    environment:
        - POSTGRESHOST=ctdatabase
        - VIRTUAL_HOST=ctobservatory.org
        - VIRTUAL_PORT=7801
    links:
        - ctdatabase:ctdatabase
    ports:
        - 7801:7801
    command: ./startup.sh #python /observatory/manage.py runserver 0.0.0.0:7801 #TODO use WSGI

ctanalyzer:
    dockerfile: analyzer/Dockerfile
    build: .
    environment:
        - POSTGRESHOST=ctdatabase
    links:
        - ctdatabase:ctdatabase
    command: python /analyzer/analyzer.py --pg=ctdatabase --t=60 -m -u -l
