elasticsearch:
    image: elasticsearch:latest
    volumes:
        - /mnt/data/ct-infrastructure/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
        - 9200:9200
        - 9300:9300

kibana:
    image: kibana:latest
    links:
        - elasticsearch:elasticsearch
    ports:
        - 5601:5601

ctdatabase:
    restart: always
    dockerfile: database/Dockerfile
    build: .
    entrypoint: /config.sh
    volumes:
        - /mnt/data/ct-infrastructure/ct-monitor/data:/var/lib/postgresql/data
    ports:
        - 5432:5432
    command: postgres

ctmonitor:
    restart: always
    dockerfile: monitor/Dockerfile
    build: .
    links:
        - ctdatabase:ctdatabase
    command: ./ct-monitor

ctobservatory:
    restart: always
    dockerfile: observatory/Dockerfile
    build: .
    volumes:
        - /mnt/data/ct-infrastructure/ct-monitor/misc:/static/data
    environment:
        - POSTGRESHOST=ctdatabase
        - VIRTUAL_HOST=localhost
        - VIRTUAL_PORT=7801
    links:
        - ctdatabase:ctdatabase
    ports:
        - 80:80
        - 443:443

ctanalyzer:
    dockerfile: analyzer/Dockerfile
    build: .
    volumes:
        - /mnt/data/ct-infrastructure/ct-monitor/misc:/data
    environment:
        - POSTGRESHOST=ctdatabase
    links:
        - ctdatabase:ctdatabase
        - elasticsearch:elasticsearch
        - ctobservatory:ctobservatory
    command: python2 /analyzer/analyzer.py --pg=ctdatabase --es=elasticsearch --web=ctobservatory --t=60 -m -u -l -e
