ctdatabase:
    restart: always
    dockerfile: database/Dockerfile
    build: .
    entrypoint: /config.sh
    volumes:
        - /mnt/data/ct-monitor/data:/var/lib/postgresql/data
    ports:
        - 5432:5432
    command: postgres

ctmonitor:
    restart: always
    dockerfile: monitor/Dockerfile
    build: .
    links:
        - ctdatabase:ctdatabase
    command: ./ct-monitor

ctobservatory:
    restart: always
    dockerfile: observatory/Dockerfile
    build: .
    environment:
        - POSTGRESHOST=ctdatabase
    links:
        - ctdatabase:ctdatabase
    ports:
        - "8000:8000"
    command: python /observatory/manage.py runserver 0.0.0.0:8000

ctanalyzer:
    dockerfile: analyzer/Dockerfile
    build: .
    environment:
        - POSTGRESHOST=ctdatabase
    links:
        - ctdatabase:ctdatabase
