ctmonitor:
  restart: always
  build: .
  dockerfile: Dockerfile
  entrypoint: /config.sh
  volumes:
    - /mnt/data/ct-monitor/data:/var/lib/postgresql/data
  ports:
    - 5432:5432
  command: postgres

#ct-observtory:
#  image: usecap/binary-analysis
#  links:
#    - ct-monitor:ct-monitor
